name: travelmap3
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.30.0
  cloud_firestore: ^4.17.0
  firebase_auth: ^4.19.6
  firebase_storage: ^11.7.7

  # Geolocalização e Mapa (Nova Configuração)
  geolocator: ^12.0.0
  flutter_map: ^6.1.0 # Pacote de mapa principal
  latlong2: ^0.9.0    # Pacote auxiliar para coordenadas

  # Funcionalidades do App
  image_picker: ^1.1.2
  flutter_rating_bar: ^4.0.1
  cached_network_image: ^3.3.1

  # Ícones
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
