// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVNPwGVn-3dezJuK6pPm2PjLZFlbaYXRs',
    appId: '1:494811837907:web:00e4f3bdbc7df6b3976b26',
    messagingSenderId: '494811837907',
    projectId: 'travelmap-5d740',
    authDomain: 'travelmap-5d740.firebaseapp.com',
    storageBucket: 'travelmap-5d740.firebasestorage.app',
    measurementId: 'G-0K5E3NJNPF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPalKe9MCr_HdB5RlFzN1VQ9L2WeI1LpY',
    appId: '1:494811837907:android:93c45b3b9e42c2c6976b26',
    messagingSenderId: '494811837907',
    projectId: 'travelmap-5d740',
    storageBucket: 'travelmap-5d740.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCI3NKuCDoaWLn10VKZHC-kHJrxvHi7LwQ',
    appId: '1:494811837907:ios:3e45a6ceea2c561c976b26',
    messagingSenderId: '494811837907',
    projectId: 'travelmap-5d740',
    storageBucket: 'travelmap-5d740.firebasestorage.app',
    iosBundleId: 'com.example.travelmap2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCI3NKuCDoaWLn10VKZHC-kHJrxvHi7LwQ',
    appId: '1:494811837907:ios:3e45a6ceea2c561c976b26',
    messagingSenderId: '494811837907',
    projectId: 'travelmap-5d740',
    storageBucket: 'travelmap-5d740.firebasestorage.app',
    iosBundleId: 'com.example.travelmap2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCVNPwGVn-3dezJuK6pPm2PjLZFlbaYXRs',
    appId: '1:494811837907:web:5be26163f86d66ca976b26',
    messagingSenderId: '494811837907',
    projectId: 'travelmap-5d740',
    authDomain: 'travelmap-5d740.firebaseapp.com',
    storageBucket: 'travelmap-5d740.firebasestorage.app',
    measurementId: 'G-5VB15ZDXQM',
  );
}
